### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by johanhelsing** [EastingAndNorthing/three#1]
We're doing some rigid body xpbd experiments with Bevy and rust. Would be cool to compare notes and implementation.

Currently this project doesn't have a license, though, so I'm a bit reluctant to look too closely at it. Would you mind if we end up using parts of your implementation to compare and fix issues in [bevy_xpbd](https://github.com/Jondolf/bevy_xpbd)?

https://github.com/Jondolf/bevy_xpbd/issues/2 in particular.

**Comment by EastingAndNorthing** [comment]
Awesome! 

I'm open to help you guys out. I've added an MIT license for this project, since Matthias published his version of PBD.js under that license as well. 

[My solver](https://github.com/EastingAndNorthing/three/blob/master/src/physics/solver/XPBDSolver.ts) has most of the equations from the XPBD paper implemented, but there are a few instances where I had to modify an equation (e.g. negating a result). I've gone over it at least 10 times, and I've added comments for each section as well. I'd say it's around 90% of the way there. 

Keep in mind that some of my code uses parts from THREE.js (e.g. AABBs and convex hull generation). 

Feel free to look around my codebase and let me know if you have any specific questions.
